version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/perfume-pedia:latest
    container_name: perfume-pedia
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/perfumePedia?serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    volumes:
      - /home/argo/Perfume-project/Docker:/app/data
    depends_on:
      - db
    networks:
      - perfume-network

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}  # root 비밀번호 설정
      - MYSQL_DATABASE=perfumePedia
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - perfume-network

volumes:
  mysql_data:

networks:
  perfume-network:
    driver: bridge
