# main 브랜치로 Pull-Request 시 빌드 및 테스트를 검증하는 CI 워크플로우

name: PR 테스트(BE)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Gradle 캐시
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-

      - name: Gradle 권한 설정
        run: chmod +x ./gradlew

      - name: 빌드 실행 (테스트 제외)
        id: build
        run: |
          if ./gradlew build -x test; then
            echo "BUILD_STATUS=success" >> $GITHUB_ENV
          else
            echo "BUILD_STATUS=failure" >> $GITHUB_ENV
          fi

      - name: 빌드 실패 시 코멘트
        if: env.BUILD_STATUS == 'failure'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🔴 빌드에 실패했습니다.😭 코드를 확인해주세요!

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3

      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

#      - name: Gradle 캐시
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-

      - name: Gradle 권한 설정
        run: chmod +x ./gradlew

      - name: 테스트 실행
        run: ./gradlew test

      - name: 테스트 실패 시 코멘트
        if: failure()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🔴 테스트가 실패했습니다.😭 코드를 확인해주세요!
